### ISSUE TITLE
Lägg till Tobias Sandelius bland medarbetare

### ISSUE THREAD

**Issue by alex-ross** [standout/standout.se#70]
@sandelius skapa dig själv och lägg upp dig bland medarbetare. Albert eller David kan nog hjälpa till med att ta en bild om du inte redan har en du vill använda.

Här ska den finnas: http://standout.se/medarbetare/

**Comment by davidelbe** [comment]
Jag har ju redan en bild på @sandelius som användes på Facebook - den kan vi nog använda även här.
